config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dashboard
  resources :profiles
  resources :home

  root to: "home#index"
    get 'profiles/:id' => 'profiles#edit'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	# attr_accessible :user_id, :name, :gender, :dob, :profession, :mobile_no
	validates :name, :presence => 'true'
  	validates :gender, :presence => 'true'					
  	validates :dob, :presence => 'true'
  	validates :profession, :presence => 'true'
  	validates :mobile_no, :presence => 'true' , :numericality => {:only_integer => true}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to :controller => 'profiles', :action => 'index'
		end
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_filter :authenticate_user!
	before_action :set_profile, only: [:show, :edit, :update, :destroy]
	
	def index
		if user_signed_in?
			@profiles = Profile.all
		end 
	end

	def show
		@profiles = Profile.all
	end
	
	def edit
		@profile = Profile.update
	end

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_params)

		respond_to do |prfl|
			if @profile.save
				prfl.html{ redirect_to @profile, notice: 'profile was successfully created' }
				prfl.json{ render :show, status: :created, location: @profile }
			else
				prfl.html{ render :new }
				prfl.json{ render json: @profile.errors, status: :unprocessible_entity }
			end
		end
	end

	def update
	    respond_to do |prfl|
	      if @profile.update(profile_params)
	        prfl.html { redirect_to @profile, notice: 'profile was successfully updated.' }
	        prfl.json { render :show, status: :ok, location: @profile }
	      else
	        prfl.html { render :edit }
	        prfl.json { render json: @profile.errors, status: :unprocessable_entity }
	      end
	    end
  	end

	private
	def set_profile
      @profile = Profile.find(params[:id])
      @profile = Profile.all
    end

	def profile_params
      params.require(:profile).permit( :user_id, :name, :gender, :dob, :profession, :mobile_no)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary menu navbar-right' %>
	<%= link_to "Log in", user_session_path, :class => 'btn btn-primary menu navbar-right' %>
</nav>
<div style = "padding-top:50px">
	<h1>Welcome to Your Home</h1>
</div>
<style type = "text/css">
  .menu{
    padding: 6px;
    margin: 8px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseUserform</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |name,msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	<div class = "container">
		<%= yield %>
	</div>	
	
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :class => "form-horizontal profile", multipart: true  } do |f| %>
   
  <div class = "container">
     
    <div class="form-group">
      <%= f.label :user_id, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :user_id, :class => 'form-control' %>
      </div>
    </div>
   
    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>
   
    <div class="form-group">
      <%= f.label :gender, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :gender, :class => 'form-control' %>
      </div>
    </div>
   
    <div class="form-group">
      <%= f.label :dob, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :dob, :class => 'form-control' %>
      </div>
    </div>
   
    <div class="form-group">
      <%= f.label :profession, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :profession, :class => 'form-control' %>
      </div>
    </div>
   
    <div class="form-group">
      <%= f.label :mobile_no, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :mobile_no, :class => 'form-control' %>
      </div>
    </div>

     <div class="form-group">
      <div class="col-sm-offset-4 col-sm-4">
        <%= f.submit nil, :class => 'btn btn-primary' %>
      </div>
    </div>

  </div>  
<% end %>

app/views/profiles/edit.html.erb
<div class="page-header">
  <h1>Edit Profile</h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<% if user_signed_in? %>
  
    <% if current_user.profile %>
      <nav class="navbar navbar-default navbar-fixed-top">
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary navbar-right menu' %>
      </nav>
      
      <div style = "padding-top:50px">
        <strong>Current User Details:</strong><br>
        Signed in as <strong><%= current_user.email %></strong>.<br>
        <h1>Welcome to Your Profile</h1>
      </div>

      <dl class="dl-horizontal">
      
        <dt><strong>Name</strong>:</dt><dd><%= current_user.profile.name %></dd>
      
        <dt><strong>Gender</strong>:</dt><dd><%= current_user.profile.gender %></dd>
      
        <dt><strong>DOB</strong>:</dt><dd><%= current_user.profile.dob %></dd>
      
        <dt><strong>Profession</strong>:</dt><dd><%= current_user.profile.profession %></dd>

      </dl>
      <% @profiles.each do |prfl| %>
        <%= link_to 'edit', :method => :edit, :class => 'btn btn-default btn-xs' %>
      <%end%>
    <% else %> 
      <nav class="navbar navbar-default navbar-fixed-top">       
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary navbar-right menu' %> 
        <%= link_to "Create profile", new_profile_path, :method => :get, :class => 'btn btn-primary navbar-right menu' %>
      </nav>
      <div style = "padding-top:50px">
        <strong><%= current_user.email %></strong> has no profile. If you want to create your profile goto  <%= link_to 'create profile', new_profile_path %>         
      </div>
    <% end %>        
<% end %> 
       
<script type = "text/javascript">
$(document).on("click", "#viewclick", function(){
     $('.view_current_profile').fadeOut();
});
  
</script> 

<style type = "text/css">
  .menu{
    padding: 6px;
    margin: 8px;
  }
</style>



 

app/views/profiles/new.html.erb
<div class="page-header">
  <h1 style="text-align:center">Create Profile</h1>
</div>

<%= render :partial => 'form' %>
	
 <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary' %>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1>Profile</h1>
</div>
  <%= current_user.email %>
  <h1>Profile created Successfully</h1>
         
 <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary' %>        